on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  lints:
    name: Rust lints
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: fmt
          args: -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        continue-on-error: false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- --deny warnings

  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: build
          args: --locked

      - uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test
          args: --locked